TP-3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP_3.Models;

namespace TP_3.Controllers
{
    public class HomeController : Controller
    {
        private bdgplccEntities db = new bdgplccEntities();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            string username=null, mdp=null;
            string nomUtilisateur = collection["nomUtilisateur"];
            var dejaMembre = db.membres.Where(m => m.nomUtilisateur == nomUtilisateur).ToList();
            foreach(var mb in dejaMembre)
            {
                username = mb.nomUtilisateur;
                mdp = mb.mdp;
            }
            if(dejaMembre != null)
            {
                if (username != null && mdp == collection["mdp"])
                {
                    HttpContext.Session["username"] = collection["nomUtilisateur"];
                    return RedirectToAction("Index", "livres", new { categ = "all" });
                }
                ViewBag.Error = "Nom d'utilisateur ou mot de passe incorrect";
                return View();
            }
            return View("~/Views/Shared/Error.cshtml");

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult SeDeconecter()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Admin()
        {
            string messAjoutLivre = TempData["MessAjoutLivre"] as string;
            ViewBag.MessAjoutLivre = messAjoutLivre;
            return View();
        }
    }
}

TP-3/Controllers/membresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TP_3.Models;

namespace TP_3.Controllers
{
    public class membresController : Controller
    {
        private bdgplccEntities db = new bdgplccEntities();

        // GET: membres
        public ActionResult Index()
        {
            string messSupp = TempData["MessSupp"] as string;
            ViewBag.messSupp = messSupp;

            string messModif = TempData["messModif"] as string;
            ViewBag.messModif = messModif;
            return View(db.membres.ToList());
        }

        // GET: membres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            membre membre = db.membres.Find(id);
            if (membre == null)
            {
                return HttpNotFound();
            }
            return View(membre);
        }

        // GET: membres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: membres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,prenom,nom,nomUtilisateur,email,telephone,mdp")] membre membre)
        {
            if (ModelState.IsValid)
            {
                HttpContext.Session["username"] = membre.nomUtilisateur;
                db.membres.Add(membre);
                db.SaveChanges();
                return RedirectToAction("Index", "livres", new { categ = "all" });
            }

            return View(membre);
        }

        // GET: membres/Edit/
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            membre membre = db.membres.Find(id);
            if (membre == null)
            {
                return HttpNotFound();
            }
            return View(membre);
        }

        // POST: membres/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,prenom,nom,nomUtilisateur,email,telephone,mdp")] membre membre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(membre).State = EntityState.Modified;
                db.SaveChanges();
                TempData["messModif"] = "Vous venez de modifier les informations de " + membre.nomUtilisateur;
                return RedirectToAction("Index");
            }
            return View(membre);
        }

        // GET: membres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            membre membre = db.membres.Find(id);
            if (membre == null)
            {
                return HttpNotFound();
            }
            return View(membre);
        }

        // POST: membres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            membre membre = db.membres.Find(id);
            db.membres.Remove(membre);
            db.SaveChanges();
            TempData["MessSupp"] = "Vous venez de supprimer le membre " + membre.nomUtilisateur + ".";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TP-3/Controllers/retardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TP_3.Models;

namespace TP_3.Controllers
{
    public class retardsController : Controller
    {
        private bdgplccEntities db = new bdgplccEntities();

        // GET: retards
        public ActionResult Index()
        {
            return View(db.retards.ToList());
        }

        // GET: retards/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            retard retard = db.retards.Find(id);
            if (retard == null)
            {
                return HttpNotFound();
            }
            return View(retard);
        }

        // GET: retards/Create
        public ActionResult Create()
        {
            var listePret = db.prets.ToList();
            var retards = db.retards.ToList();
            string dateRetour;
            DateTime dr;
            retard nouvRetard;
            var tab = new List<retard> { };
            bool existeDeja = false;

            foreach (var pret in listePret)
            {
                //verification sinexiste deja dans retard
                foreach (var retard in retards)
                {
                    if (retard.ISBN == pret.ISBN)
                    {
                        existeDeja = true;
                    }
                }
                dateRetour = pret.dateRetour;
                DateTime.TryParseExact(dateRetour, "yy/MM/dd", System.Globalization.CultureInfo.GetCultureInfo("fr-FR"), System.Globalization.DateTimeStyles.None, out dr);

                if (DateTime.Compare(dr, DateTime.Now) < 0 && existeDeja == false)
                {
                    nouvRetard = new retard
                    {
                        nom = pret.nom,
                        nomUtilisateur = pret.nomUtilisateur,
                        ISBN = pret.ISBN,
                        categories = pret.categories,
                        auteur = pret.auteur,
                        datePret = pret.datePret,
                        dateRetour = pret.dateRetour
                    };
                    db.retards.Add(nouvRetard);
                    db.SaveChanges();
                }

            }
            return RedirectToAction("Index");
        }

        // POST: retards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
       /* [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,nomUtilisateur,ISBN,nom,categories,auteur,datePret,dateRetour")] retard retard)
        {
            if (ModelState.IsValid)
            {
                db.retards.Add(retard);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(retard);
        }*/

        // GET: retards/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            retard retard = db.retards.Find(id);
            if (retard == null)
            {
                return HttpNotFound();
            }
            return View(retard);
        }

        // POST: retards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,nomUtilisateur,ISBN,nom,categories,auteur,datePret,dateRetour")] retard retard)
        {
            if (ModelState.IsValid)
            {
                db.Entry(retard).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(retard);
        }

        // GET: retards/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            retard retard = db.retards.Find(id);
            if (retard == null)
            {
                return HttpNotFound();
            }
            return View(retard);
        }

        // POST: retards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            retard retard = db.retards.Find(id);
            db.retards.Remove(retard);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TP-3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TP-3/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}

<h2>Gestion des tables de données</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Tables de données</th>
            <th scope="col"></th>
            <th scope="col" width="50%">Gestions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Prêts</th>
            <td>@Html.ActionLink("Lister", "IndexGestion", "prets")</td>
            <td></td>
        </tr>
        <tr>
            <th scope="row">Retards</th>
            <td>@Html.ActionLink("Lister", "Create", "retards")</td>
            <td></td>
        </tr>
        <tr>
            <th scope="row">Membres</th>
            <td>@Html.ActionLink("Lister + Modifier + Supprimer", "Index", "membres")</td>
            <td></td>
        </tr>
        <tr>
            <th scope="row">Livres</th>
            <td>@Html.ActionLink("Lister + Modifier + Supprimer", "IndexList", "livres", new { }, null)</td>
            <td>@Html.ActionLink("Ajouter", "Create", "livres")</td>
        </tr>
    </tbody>
</table>

@{
    
    if (ViewBag.MessAjoutLivre != null)
    {
        <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Message</h4>
                    </div>
                    <div class="modal-body">
                        <p>@ViewBag.MessAjoutLivre</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $('#myModal').modal('show')
        </script>
    }
    
    }

TP-3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TP-3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div id="headerImage">
    <h1>Bienvenue à votre bibliothèque virtuel</h1>
</div>

<h3>Connectez-vous</h3>

<form method="post" name="formSeConnecter" action="@Url.Action("Index", "Home")">
    <div class="form-group">
        <label for="exampleInputusername">Nom d'utilisateur</label>
        <input type="text" name="nomUtilisateur" class="form-control" id="exampleInputusername" placeholder="nom d'utilisateur">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Mot de passe</label>
        <input type="password" name="mdp" class="form-control" id="exampleInputPassword1" placeholder="mot de passe">
    </div>
    <button type="submit" class="btn btn-primary" onclick="formSeConnecter.submit();">se connecter</button><br /><br />
    <a href="/membres/Create">Vous n'êtes pas membre? Devenez-le maintenant.</a>
</form>


@{
    if (ViewBag.Error != null)
    {
        <div id="Error" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Message</h4>
                    </div>
                    <div class="modal-body">
                        <p>@ViewBag.Error</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $('#Error').modal('show')
        </script>
    }
}